import { Geist, Geist_Mono, Bebas_Neue, Palanquin } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebas_neue = Bebas_Neue({
  subsets: ["latin"],
  variable: "--font-bebas-neue",
  weight: "400"
});

const palanquin = Palanquin({
  subsets: ["latin"],
  variable: "--font-palanquin",
  weight: "400"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bebas_neue.variable} ${palanquin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
